### Site metadata ###

site_name: Job coding assignment 
site_description: Job coding assignment 
site_url: https://ujstor.github.io/coding-assignment/

repo_url: https://github.com/Ujstor/coding-assignment

### Build settings ###

theme:
  name: material
  custom_dir: custom_theme/
  theme:
  features:
    - navigation.instant
    - navigation.expand
    - toc.flow
    - navigation.top
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/ujstor
        name: GitHub
    generator: false
copyright: Copyright &copy; 2024 Ujstor
