### Site metadata ###

site_name: Infra assignment 
site_description: Infra assignment 
site_url: https://ujstor.github.io/infra-assignment/

repo_url: https://github.com/Ujstor/infra-assignment

### Build settings ###

theme:
  name: material
  custom_dir: custom_theme/
  theme:
  features:
    - navigation.instant
    - navigation.expand
    - toc.flow
    - navigation.top
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Terraform: 
    - Assigment: terraform.md
    - Resurces: terraform/resources.md
  - Kubernetes: 
    - Assigment: kubernetes.md

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/ujstor
        name: GitHub
    generator: false
copyright: Copyright &copy; 2024 Ujstor
